# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 100c2be586d8fe581a18524fa5b2eb114b1ce1122a636ef56874da74382812ce4087c8e76f7e70e1e19e44e3e8c406863345b1274530020863a20cddfc1786bf

test:
  secret_key_base: fc207393368ad7ba55e87e2aa4826e89841862665350d92665671150357c4dab33e6d30ac2e1e13f9e63a9a1b1dbc3096f1f397e43ba12b3fb52e38d031d3689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
